export const SET_ARTICLE_LOADED_TRUE = 'SET_ARTICLE_LOADED_TRUE';
export const SET_ARTICLE_LOADED_FALSE = 'SET_ARTICLE_LOADED_FALSE';
export const GET_ARTICLE = 'GET_ARTICLE';
export const SAVE_ARTICLE = 'SAVE_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const SET_ARTICLE_UNLOADED_TRUE = 'SET_ARTICLE_UNLOADED_TRUE';
export const SET_ARTICLE_UNLOADED_FALSE = 'SET_ARTICLE_UNLOADED_FALSE';

export const SAVE_ARTICLE_LIST = 'UPDATE_ARTICLE_LIST';
export const CHANGE_PAGINATION = 'CHANGE_PAGINATION';
export const RESET_LOADING = 'RESET_LOADING';

export const LOADING_START = `LOADING_START`;
export const LOADING_STOP = `LOADING_STOP`;
export const START_LOADING_ARTICLE = 'START_LOADING_ARTICLE';
export const STOP_LOADING_ARTICLE = 'STOP_LOADING_ARTICLE';
export const START_LOADING_ARTICLE_LIST = 'START_LOADING_ARTICLE_LIST';
export const STOP_LOADING_ARTICLE_LIST = 'STOP_LOADING_ARTICLE_LIST';

export const SAVE_USER = `SAVE_USER`;
export const DELETE_USER = `DELETE_USER`;
export const LOG_IN = `LOG_IN`;
export const LOG_OUT = `LOG_OUT`;
